### ISSUE TITLE
Improve robustness

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/invenio-converter#3]
## To-Do
- [ ] Create test for working of container
- [ ] Find or create Invenio Json Schema
- Include validation of output against invenio json schemas:
  - [ ] At Runtime 
  - [ ] At Compile time (unit test)

## Additional ressources: 
- Invenio json schema: None?

- Validation package: 
  https://www.nuget.org/packages/ISADotNet.Validation/
  ```fsharp
  #r "nuget: ISADotNet.Validation, 0.6.1"

  open ISADotNet.Validation

  JSchema.Validate jsonSchemaUrl jsonString
  
  ```

- Validation source code: https://github.com/nfdi4plants/ISADotNet/blob/512f982d0bb79e0fc94c317e22785d70c71dd55d/src/ISADotNet.Validation/JsonSchemaValidation.fs#L15
